create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null,
  phone text,
  specialization text,
  avatar text,
  createdAt timestamptz default now()
);

create table if not exists patients (
  id bigint generated by default as identity primary key,
  userId bigint,
  name text not null,
  age integer not null,
  gender text not null,
  bloodGroup text,
  condition text not null,
  illness text,
  allergies text,
  emergencyContact text,
  assignedDoctorId bigint,
  assignedCaretakerId bigint,
  weight numeric,
  height numeric,
  illnessHistory jsonb default '[]'::jsonb,
  treatments jsonb default '[]'::jsonb,
  doctorNotes jsonb default '[]'::jsonb,
  createdAt timestamptz default now()
);

create table if not exists prescriptions (
  id bigint generated by default as identity primary key,
  patientId bigint not null,
  doctorId bigint,
  medicine text not null,
  dosage text not null,
  frequency text not null,
  duration text,
  status text default 'pending',
  notes text,
  createdAt timestamptz default now()
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  level text default 'low',
  patientId bigint,
  read boolean default false,
  createdAt timestamptz default now()
);

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  patientId bigint not null,
  patientName text,
  doctorId bigint,
  doctorName text,
  date text not null,
  time text not null,
  type text,
  status text default 'scheduled'
);

create table if not exists logs (
  id bigint generated by default as identity primary key,
  patientId bigint,
  patientName text,
  date text,
  note text not null,
  by text,
  temperature text,
  bloodPressure text,
  sugar text,
  createdAt timestamptz default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  patientId bigint not null,
  title text not null,
  type text,
  status text default 'pending',
  uploadedBy text,
  reviewedBy text,
  notes text,
  createdAt timestamptz default now()
);

create table if not exists devices (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  status text default 'offline',
  patientId bigint,
  pillsRemaining integer default 0,
  pillsDispensed integer default 0,
  lastSync timestamptz default now()
);
